eureka:
  client:
    # 向注册中心注册
    fetch-registry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.27.140/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: 192.168.27.1
logging:
  file: "/home/mect/log/${spring.application.name}/${spring.application.name}.log"
  level:
    com.medcaptain.cloud.usermanage.mapper: debug
spring:
  boot:
    admin:
      client:
        url: "http://192.168.81.31:5000"
  redis:
    cluster:
      nodes: "192.168.27.140:7001,192.168.27.140:7002,192.168.27.140:7003,192.168.27.140:7004,192.168.27.140:7005,192.168.27.140:7006"

#druid数据库连接池配置
druid:
  jdbc-driver: "com.mysql.jdbc.Driver"
  db-url: "jdbc:mysql://192.168.27.140:3306/cloud_user?useSSL=false&serverTimezone=UTC&&characterEncoding=UTF-8&&useUnicode=true&amp"
  username: "root"
  password: "123"
  filter: "stat"
  max-active: 150
  max-wait: 30000
  min-idle: 5
  time-between-eviction-runs-millis: 60000
  min-evictable-idle-time-millis: 30000
  test-while-idle: true
  validation-query: "select 'x' from dual"
  test-on-borrow: true
  test-on-return: false
  pool-prepared-statements: false
  max-open-prepared-statements: -1
  remove-abandoned: true
  remove-abandoned-timeout: 180

user-manage:
  user-token-expire-seconds: 2000
  third-part-user-token-expire-seconds: 7200
  login-fail-expire-seconds: 120
  captcha-expire-seconds: 300
  role-permission-expire-days: 7  

server:
  port: 8760
