spring:
  application:
    name: zuul

server:
  port: 80

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 3000

security:
  basic:
    enable: true
  user:
    name: root
    password: zuul

zuul:
  routes:
    configserver: /config/**
